### ISSUE TITLE
Support for UTF8 characters

### ISSUE THREAD

**Issue by LittleHelicase** [BuggyOrg/lisgy#10]
This does not work:

![image](https://cloud.githubusercontent.com/assets/5698911/16589158/24bbde94-42d2-11e6-84ae-35b7e0c6205b.png)

The error message indicates, that special characters are not allowed, but why? Also, the error marker is located at the wrong position.

**Comment by leMaik** [comment]
Title should be changed to "Support for totally normal and easy-to-type characters everyone uses on a daily basis is missing". :wink:

**Comment by fasib** [comment]
Currently jsedn uses the following regex for symbols:
`/[0-9A-Za-z.*+!\-_?$%&=<>\/:#/]+/`
https://github.com/BuggyOrg/jsedn/blob/master/src/atoms.coffee#L44

So I think we should add something like `\u0080-\u9fff`
