### ISSUE TITLE
Imports should not be resolved when checking the syntax

### ISSUE THREAD

**Issue by leMaik** [BuggyOrg/lisgy#8]
Consider the following example:
```
(import all)
(+ 42 0
```

`checkSyntax` returns a syntax error, which is correct. But it's not in line `2`, but in line `<length of import> + 2`.

**Comment by fasib** [comment]
fixed in https://github.com/BuggyOrg/lisgy/commit/be4bd1a11ffec6ae253ccd83097c2475f746cfc2
